title: Cindy Nicasio - Programming Portfolio # your name (or website title) here
logo: "/images/profile.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! My name is Cindy Nicasio, and I'm an aspiring game artist!
  <br><br>
  I am currently a senior at Columbia College Chicago and down below is a compilation of Coding projects I have worked on so far in the semester.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
